import "./globals.css";

export const metadata = {
  title: "ByteVerse'24",
  description: "Generated by create next app",
  icons:{
    icon:['/favicons/favicon.ico?v=4'],
    apple:['/favicons/apple-touch-icon.png?v=4'],
    shortcut:['/favicons/apple-touch-icon.png']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
